# Generated by Django 3.0.4 on 2020-05-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('MovieName', models.CharField(max_length=50)),
                ('MovieType', models.CharField(max_length=50)),
                ('MovieLanguage', models.CharField(max_length=50)),
                ('MovieCast', models.CharField(max_length=50)),
                ('MovieDirector', models.CharField(max_length=50)),
                ('MovieDuration', models.CharField(max_length=50)),
                ('MovieReleaseDate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'movie_408',
            },
        ),
    ]
