# Generated by Django 3.0.4 on 2020-05-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTBApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='MovieImg',
            field=models.ImageField(default='No-img.jpg', upload_to='movieImage/'),
        ),
    ]
