# Generated by Django 3.0.4 on 2020-05-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTBApp', '0002_movie_movieimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustId', models.AutoField(primary_key=True, serialize=False)),
                ('CustFName', models.CharField(max_length=50)),
                ('CustLName', models.CharField(max_length=50)),
                ('CustEmailId', models.CharField(max_length=50)),
                ('CustPassword', models.CharField(max_length=50)),
                ('CustContactNo', models.CharField(max_length=50)),
                ('CustAddress', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer_408',
            },
        ),
    ]
