# Generated by Django 3.0.4 on 2020-05-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTBApp', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminEmailId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adminPassword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin_408',
            },
        ),
    ]
