# Generated by Django 3.0.4 on 2020-05-17 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OMTBApp', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('ShowId', models.AutoField(primary_key=True, serialize=False)),
                ('theatreNameLocation', models.CharField(max_length=100)),
                ('screen', models.CharField(max_length=20)),
                ('showDate', models.CharField(max_length=50)),
                ('showTime', models.CharField(max_length=50)),
                ('showPrice', models.FloatField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMTBApp.Movie')),
            ],
            options={
                'db_table': 'shows_408',
            },
        ),
    ]
